### ISSUE TITLE
Missing packages Linux Mint 20.2

### ISSUE THREAD

**Issue by qiray** [beremiz/beremiz#1]
Hello!

I try to install prerequisites from Readme.md on Linux Mint 20.2 and these packages are not available:

```
pyro
python-nevow
python-matplotlib
python-zeroconf
python-cycler
python-autobahn
```

What should I install for build?

**Comment by bullitmaster** [comment]
Try it with pip2:
pip2 install pyro 
and etc.

**Comment by etisserant** [comment]
Please use requirements.txt in python3 branch to install prerequisites.
