### ISSUE TITLE
EtherCAT Configurator does not run properly and many errors are reported

### ISSUE THREAD

**Issue by bruce202202** [beremiz/beremiz#13]
EtherCAT Configurator does not run properly and many errors are reported, I tried to fix it, but those issues was too complicated ！
 ```
File "~\etherlab\EtherCATManagementEditor.py", line 859, in __init__
    self.LoadPDOSelectData()
  File "~\etherlab\EtherCATManagementEditor.py", line 917, in LoadPDOSelectData
    RxPDOData = self.Controler.BaseParams.getRxPDO()
  File "~\xmlclass\xmlclass.py", line 1345, in getattrMethod
    return DefaultElementClass.__getattribute__(self, name)
AttributeError: 'BaseParams' object has no attribute 'getRxPDO'
```

**Comment by skibon02** [comment]
this part of the project was probably abandoned and i guess porting to wxPython4 and writing tests are most important tasks of the project now. 
I also saw some strange errors in modbus/ettercat implementation like missing newline or semicolon and made a decision that this code was working in previous versions. 
As an alternative you can develop your own extension for beremiz and add some custom configuration nodes and locations

**Comment by etisserant** [comment]
I confirm: EtherCAT support is not maintained since years, and is broken. Any contribution is welcome.
