### ISSUE TITLE
Beremiz bitwise handling problem

### ISSUE THREAD

**Issue by pdorokhov** [beremiz/beremiz#15]
Hi. Please advise me on this question - the compiler does not allow bitwise access to bitwise strings. What can this problem be related to, because the manual says that this is correct.

![01](https://github.com/beremiz/beremiz/assets/100029272/fc22735e-3ee6-42bc-8f97-ee9f07e87438)

![02](https://github.com/beremiz/beremiz/assets/100029272/2fdb8995-e761-423e-8261-114c484d1632)

**Comment by etisserant** [comment]
I see nowhere such syntax in IEC-61131-3. Please point where in IEC-61131-3 is this language feature defined.

**Comment by pdorokhov** [comment]
Unfortunately I cannot download the description of IEC61131-3 in English from the IEC website. I have a description of the standard in Russian, and it mentions bitwise handling, but unfortunately I can't compare it with the description of the original standard.
![image](https://github.com/beremiz/beremiz/assets/100029272/f6a87c1a-d307-4c86-b167-64a0f8e651d7)

**Comment by pdorokhov** [comment]
> I see nowhere such syntax in IEC-61131-3. Please point where in IEC-61131-3 is this language feature defined.

Unfortunately I cannot download the description of IEC61131-3 in English from the IEC website. I have a description of the standard in Russian, and it mentions bitwise handling, but unfortunately I can't compare it with the description of the original standard.
![image](https://github.com/beremiz/beremiz/assets/100029272/f6a87c1a-d307-4c86-b167-64a0f8e651d7)

**Comment by etisserant** [comment]
With your input, I could find where it is :  "6.6.1.3 Partial access to ANY_BIT variables"
This is part of IEC-61131-3 3rd edition !
3rd Edition of IEC-61131 is not supported for now, only 2nd edition is.
