### ISSUE TITLE
Error while creating an action

### ISSUE THREAD

**Issue by jchan93** [beremiz/beremiz#23]
It's impossible to create and use an action in python3

![Capture d'écran 2023-10-11 164126](https://github.com/beremiz/beremiz/assets/147632108/49279658-e73e-4705-8294-7022cf2c276b)
![Capture d'écran 2023-10-11 164150](https://github.com/beremiz/beremiz/assets/147632108/d5e4aba3-ead8-4d1c-b7dd-f9eabe5c48c2)

[bug_report_2023_10_11__16-41-34.txt](https://github.com/beremiz/beremiz/files/12871333/bug_report_2023_10_11__16-41-34.txt)

Thanks for your work on beremiz,
Jonathan Chan

**Comment by etisserant** [comment]
Should be fixed in 94e42cda0a8e093aac4830b5c40656c240ec8cf9.
Please test further and confirm.
Thanks for reporting !

**Comment by jchan93** [comment]
Hello, i think there's a deeper bug due to the migration with python3. In fact, when you create an **action** and implement  **blocks**, these **blocks** disappear when you reclick on the action. The variable of the **program** is still there, however.
![Capture d'écran 2023-10-13 094551](https://github.com/beremiz/beremiz/assets/147632108/40cd7d7f-df25-49f0-a2c4-d688f3a21c51)
![Capture d'écran 2023-10-13 094927](https://github.com/beremiz/beremiz/assets/147632108/9b3d4225-a6b6-40f1-8d4f-044b01b206d2)

To help you with the bug i tried to debug this on vscode and when you create a **block** inside the **action** there is an assertion who pop up only in debug terminal :

C:\Developpement\TestBeremiz\Beremiz_V3\beremiz\editors\Viewer.py:637: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  menu.AppendMenu(-1, _('Add'), add_menu)
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\common\wincmn.cpp(3453) in DoNotifyWindowAboutCaptureLost(): window that captured the mouse didn't process wxEVT_MOUSE_CAPTURE_LOST  

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.MouseEvent'> returned a result with an exception set
Traceback (most recent call last):
  File "c:\Developpement\TestBeremiz\Beremiz_V3\env\lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Developpement\TestBeremiz\Beremiz_V3\beremiz\util\ExceptionHandler.py", line 54, in Display_Exception_Dialog
    cap.ReleaseMouse()
wx._core.wxAssertionError: C++ assertion ""!wxMouseCapture::stack.empty()"" failed at ..\..\src\common\wincmn.cpp(3426) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?
Traceback (most recent call last):
  File "c:\Developpement\TestBeremiz\Beremiz_V3\env\lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Developpement\TestBeremiz\Beremiz_V3\beremiz\util\ExceptionHandler.py", line 54, in Display_Exception_Dialog
    cap.ReleaseMouse()
wx._core.wxAssertionError: C++ assertion ""!wxMouseCapture::stack.empty()"" failed at ..\..\src\common\wincmn.cpp(3426) in wxWindowBase::ReleaseMouse(): Releasing mouse capture but capture stack empty?

**Comment by etisserant** [comment]
Given backtrace is unrelated side effect of showing exception dialog together with vscode debugging. Comment-out self.InstallExceptionHandler() in Beremiz.py to avoid this.

I reverted previous commit, that was not really solving the problem indeed - not even close.

b081c8bea85a58c6101249b7be5f235220632373 fixes it.
