### ISSUE TITLE
wrong python path in the readme

### ISSUE THREAD

**Issue by ouinouin** [beremiz/beremiz#34]
to launch beremiz th doc states :

`~/Beremiz/venv/python ~/Beremiz/beremiz/Beremiz.py`
should it be :
` ~/Beremiz/venv/bin/python ~/Beremiz/beremiz/Beremiz.py`
?
at least on unbutu 22.04 python command ins in the bin subfolder.
regards.

**Comment by ywwuyi-rice** [comment]
By the way,is python path `beremiz\msys64\ucrt64\bin\python.exe` in windows if using windows installer?

**Comment by etisserant** [comment]
Thanks for reporting. Fixed in 34d4c77ccb1bcb14601ab347ec6080466b7e143d
