### ISSUE TITLE
XML parsing is broken for lxml > 4.6.2

### ISSUE THREAD

**Issue by thiagoralves** [beremiz/beremiz#4]
When lxml version is greater than 4.6.2 Beremiz cannot parse the XML correctly, ending up with the name 'derived' for every function block in the project.

Steps to reproduce:
1. Install latest lxml from pip (at the time of this writing lxml==4.9.1)
2. Clone Beremiz repo (either wxPython 4 or default - same issue on both)
3. Launch Beremiz and open first_steps project (File -> Tutorials and Examples -> first_steps)
This is a screenshot with lxml==4.9.1, libxml==2.9.14, libxslt==1.1.35
![image](https://user-images.githubusercontent.com/8240060/186272674-42f0f758-edf6-4eac-8200-96ef915c7bb0.png)

If lxml is downgraded to 4.6.2 the problem disappears. Screenshot below:
![image](https://user-images.githubusercontent.com/8240060/186272924-ca1f5f75-10d0-4f61-a183-163c8d541c49.png)

It is impossible to compile any project that has a function block with this parsing issue, as the generated ST code comes up with the type of each block as 'derived' instead of the correct type (COUNTERST, COUNTERFBD, etc)

**Comment by etisserant** [comment]
LXML has no problem to parse XML, but with recent LXML versions, a particular XSLT transform gives wrong results.
Latest Windows installer and Snap package work around this by bundling an older version of LXML.

It is really probably a bug in LXML. When I'll find the details why it breaks that particular XSLT transform I will report to LXML team, and there will be a new version of LXML ==> Won't fix, please use older version.

If on a hurry to fix this, maybe you can make an issue in that really lame copy of Beremiz [here](https://github.com/thiagoralves/OpenPLC_Editor) , and serve yourself.  Good luck.
