### ISSUE TITLE
The OPC UA module cannot be used

### ISSUE THREAD

**Issue by yjtdgs** [beremiz/beremiz#6]
I tried to install the Beremiz default version in Ubuntu, but when I tried to open the OPC UA Client module after the successful installation, I would get an error. Is it because the module is not fully developed, or the Phenox version can work?

**Comment by MatthewReed303** [comment]
Having similar issue on Windows, OPC-UA/CanOpen/EtherCat Master do not work and just get bug reports. Only Modbus works.

**Comment by vitw** [comment]
> Having similar issue on Windows, OPC-UA/CanOpen/EtherCat Master do not work and just get bug reports. Only Modbus works.

I tried CANopen on default branch of Beremiz and it works perfectly.

**Comment by etisserant** [comment]
OPC UA seems working since automated tests passes. Please use latest version from python3 branch, and install open62541. Have a look in tests/Makefile and tests/tools/Docker/Dockerfile for details
